// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    HomeBannerSection: typeof import('./src/components/HomeBannerSection.vue')['default']
    HomePortfolioSection: typeof import('./src/components/HomePortfolioSection.vue')['default']
    HomeSkillsetSection: typeof import('./src/components/HomeSkillsetSection.vue')['default']
    HomeTimelineSection: typeof import('./src/components/HomeTimelineSection.vue')['default']
    IconBootstrap: typeof import('./src/components/IconBootstrap.vue')['default']
    IconCode: typeof import('./src/components/IconCode.vue')['default']
    IconCSS: typeof import('./src/components/IconCSS.vue')['default']
    IconDevops: typeof import('./src/components/IconDevops.vue')['default']
    IconFigma: typeof import('./src/components/IconFigma.vue')['default']
    IconGraphQL: typeof import('./src/components/IconGraphQL.vue')['default']
    IconHeart: typeof import('./src/components/IconHeart.vue')['default']
    IconMongoDB: typeof import('./src/components/IconMongoDB.vue')['default']
    IconNetCore: typeof import('./src/components/IconNetCore.vue')['default']
    IconNodejs: typeof import('./src/components/IconNodejs.vue')['default']
    IconNotebook: typeof import('./src/components/IconNotebook.vue')['default']
    IconOpenGL: typeof import('./src/components/IconOpenGL.vue')['default']
    IconPHP: typeof import('./src/components/IconPHP.vue')['default']
    IconReact: typeof import('./src/components/IconReact.vue')['default']
    IconStar: typeof import('./src/components/IconStar.vue')['default']
    IconSupabase: typeof import('./src/components/IconSupabase.vue')['default']
    IconTailwind: typeof import('./src/components/IconTailwind.vue')['default']
    IconUI: typeof import('./src/components/IconUI.vue')['default']
    IconVue: typeof import('./src/components/IconVue.vue')['default']
    IconWebGL: typeof import('./src/components/IconWebGL.vue')['default']
    IconWordpress: typeof import('./src/components/IconWordpress.vue')['default']
    IllustrationCode: typeof import('./src/components/IllustrationCode.vue')['default']
    IllustrationSphere: typeof import('./src/components/IllustrationSphere.vue')['default']
    SmoothReflow: typeof import('./src/components/SmoothReflow.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
  }
}

export { }
