// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./components/Common/Modal.vue')['default']
    Button: typeof import('./components/Common/Button.vue')['default']
    HomeBannerSection: typeof import('./components/Home/HomeBannerSection.vue')['default']
    HomeContactSection: typeof import('./components/Home/HomeContactSection.vue')['default']
    HomePortfolioSection: typeof import('./components/Home/HomePortfolioSection.vue')['default']
    HomeSkillsetSection: typeof import('./components/Home/HomeSkillsetSection.vue')['default']
    HomeTimelineSection: typeof import('./components/Home/HomeTimelineSection.vue')['default']
    IconBootstrap: typeof import('./components/Icon/IconBootstrap.vue')['default']
    IconCode: typeof import('./components/Icon/IconCode.vue')['default']
    IconCSS: typeof import('./components/Icon/IconCSS.vue')['default']
    IconDevops: typeof import('./components/Icon/IconDevops.vue')['default']
    IconEmail: typeof import('./components/Icon/IconEmail.vue')['default']
    IconFigma: typeof import('./components/Icon/IconFigma.vue')['default']
    IconGithub: typeof import('./components/Icon/IconGithub.vue')['default']
    IconGraphQL: typeof import('./components/Icon/IconGraphQL.vue')['default']
    IconHeart: typeof import('./components/Icon/IconHeart.vue')['default']
    IconMongoDB: typeof import('./components/Icon/IconMongoDB.vue')['default']
    IconNetCore: typeof import('./components/Icon/IconNetCore.vue')['default']
    IconNodejs: typeof import('./components/Icon/IconNodejs.vue')['default']
    IconNotebook: typeof import('./components/Icon/IconNotebook.vue')['default']
    IconOpenGL: typeof import('./components/Icon/IconOpenGL.vue')['default']
    IconPHP: typeof import('./components/Icon/IconPHP.vue')['default']
    IconReact: typeof import('./components/Icon/IconReact.vue')['default']
    IconSend: typeof import('./components/Icon/IconSend.vue')['default']
    IconStar: typeof import('./components/Icon/IconStar.vue')['default']
    IconSupabase: typeof import('./components/Icon/IconSupabase.vue')['default']
    IconTailwind: typeof import('./components/Icon/IconTailwind.vue')['default']
    IconUI: typeof import('./components/Icon/IconUI.vue')['default']
    IconVue: typeof import('./components/Icon/IconVue.vue')['default']
    IconWebGL: typeof import('./components/Icon/IconWebGL.vue')['default']
    IconWordpress: typeof import('./components/Icon/IconWordpress.vue')['default']
    IllustrationCode: typeof import('./components/Illustration/IllustrationCode.vue')['default']
    IllustrationSphere: typeof import('./components/Illustration/IllustrationSphere.vue')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    Modal: typeof import('./components/Common/Modal.vue')['default']
    SmoothReflow: typeof import('./components/Common/SmoothReflow.vue')['default']
    Text: typeof import('./components/Common/Text.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheMain: typeof import('./components/TheMain.vue')['default']
  }
}

export { }
